---
version: '2'

networks:
  backend:
    driver: bridge

services:
  koha:
    container_name: koha
    image: "digibib/koha:${KOHA_IMAGE_TAG}"
    networks:
      - backend
    depends_on:
      - koha_mysql
      - koha_index
      - sms
      - smtp
      - sip
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
      - MKNOD
    environment:
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "$KOHA_INSTANCE"
      KOHA_DBHOST: koha_mysql
      DEFAULT_LANGUAGE: nb-NO
      EMAIL_ENABLED: "True"
      SMTP_SERVER_HOST: mailrelay # access through network 'backend'
      SMTP_SERVER_PORT: 2525
      MESSAGE_QUEUE_FREQUENCY: 1
      SMS_SERVER_HOST: "${SMS_SERVER_HOST}"
      SMS_USER: "${SMS_USER}"
      SMS_PASS: "${SMS_PASS}"
      API_PASSPHRASE: "${API_PASSPHRASE}"
      NLBASEUSER: "${NLBASEUSER}"
      NLBASEPASS: "${NLBASEPASS}"
      NLVENDORURL: "${NLVENDORURL}"
      NLVENDORUSER: "${NLVENDORUSER}"
      NLVENDORPASS: "${NLVENDORPASS}"
      NLVENDORKEY: "${NLVENDORKEY}"
    ports:
      - "6001:6001"
      - "8080:8080"
      - "8081:8081"
    volumes_from:
      - koha_index
      - koha_state
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  koha_mysql:
    container_name: koha_mysql
    image: mysql:5.6.20
    networks:
      - backend
    cap_add:
      - MKNOD
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
    environment:
      MYSQL_DATABASE: "koha_${KOHA_INSTANCE}"
      MYSQL_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_ROOT_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_USER: "${KOHA_ADMINUSER}"
    ports:
      - "3306:3306"
    volumes_from:
      - koha_mysql_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  koha_mysql_data:
    container_name: koha_mysql_data
    image: "busybox:latest"
    volumes:
      - /var/lib/mysql

  koha_index:
    container_name: koha_index
    image: "busybox:latest"
    volumes:
      - "/var/lib/koha/${KOHA_INSTANCE}"

  koha_state:
    container_name: koha_state
    image: "busybox:latest"
    volumes:
      - "/var/lib/state"

  memcached:
    container_name: memcached
    image: "memcached:1.4.25"
    networks:
      - backend

  smtp:
    container_name: mailrelay
    image: "digibib/gosmtpd:e51ec0b872867560461ab1e8c12b10fd63f5d3c1"
    networks:
      - backend
    ports:
      - "8100:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  sms:
    container_name: smsproxy
    image: "digibib/tcp-proxy:14dc5417bf211317351a0bae084db12c64a1dd45"
    networks:
      - backend
    ports:
      - "8101:9999" # Can be removed, as we use docker networking for access
    command:
      - "/app/tcp-proxy"
      - "-vv"
      - "-r"
      - "${SMS_FORWARD_URL}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  tcpsink: # Fake webserver response, for testing
    container_name: tcpsink
    image: "alpine:3.3"
    networks:
      - backend
    ports:
      - "9999:9999"
    command:
      - "/bin/sh"
      - "-c"
      - "mkfifo pipe; while true ; do { read line<pipe;echo -e 'HTTP/1.1 200 OK\\r\\n' ; } | nc -l -p 9999 > pipe; done"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  nlsink: # Fake NL response, for testing
    container_name: nlsink
    image: "alpine:3.3"
    networks:
      - backend
    command:
      - "/bin/sh"
      - "-c"
      - "mkfifo pipe; while true ; do { read line<pipe;echo -e 'HTTP/1.1 200 OK\nContent-Type: text/xml; charset=utf-8\n\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ns0:Envelope xmlns:ns0=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://lanekortet.no\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" ns0:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n<ns0:Body>\n<ns1:hentResponse>\n<return xsi:type=\"ns1:Resultat\">\n<status xsi:type=\"xsd:boolean\">true</status>\n<melding xsi:type=\"xsd:string\">OK</melding>\n<antall_treff xsi:type=\"xsd:int\">0</antall_treff>\n<antall_poster_returnert xsi:type=\"xsd:int\">0</antall_poster_returnert>\n<neste_indeks xsi:type=\"xsd:int\">0</neste_indeks>\n<server_tid xsi:type=\"xsd:string\">2016-07-07T11:29:08</server_tid>\n</return>\n</ns1:hentResponse>\n</ns0:Body>\n</ns0:Envelope>\n' ; } | nc -l -p 9999 > pipe; done"

  elasticsearch_data:
    container_name: elasticsearch_data
    image: "busybox:latest"
    volumes:
      - /usr/share/elasticsearch/data

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.3.1
    networks:
      - backend
    ports:
      - "8200:9200"
      - "8300:9300"
    volumes_from:
      - elasticsearch_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  fuseki_data:
    container_name: fuseki_data
    image: "busybox:latest"
    volumes:
      - /data/databases/ds

  fuseki:
    container_name: fuseki
    image: "digibib/fuseki2"
    networks:
      - backend
    ports:
      - "3030:3030"
    volumes_from:
      - fuseki_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  sip:
    container_name: sip_proxy
    image: "digibib/tcp-proxy:14dc5417bf211317351a0bae084db12c64a1dd45"
    networks:
      - backend
    ports:
      - "6002:9999"
    command:
      - "/app/tcp-proxy"
      - "-vv"
      - "-r"
      - "koha:${SIP_PORT}"
      - "-replace=AB100301~AB0301"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  catalinker:
    container_name: catalinker
    build:
      context: "${LSEXTPATH}/redef/catalinker"
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - services
      - z3950proxy
    ports:
      - "8010:8010"
    environment:
      KOHA_OPAC_PORT: "http://koha:8080"
      KOHA_INTRA_PORT: "http://koha:8081"
      SERVICES_PORT: "http://services:8005"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  build_services:
    container_name: build_services
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile.build
    volumes:
      - "${LSEXTPATH}/redef/services/build:/services/build"

  services:
    container_name: services
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - build_services
      - fuseki
      - koha
    ports:
      - "8005:8005"
      - "8006:8006"
      - "5070:5070"
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
      KOHA_API_PASS_ENCRYPTED: "${KOHA_API_PASS_ENCRYPTED}"
      Z3950_PROXY_PORT: "http://z3950proxy:3000"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  patron_client:
    container_name: patron_client
    build:
      context: "${LSEXTPATH}/redef/patron-client"
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - services
    ports:
      - "8000:8000"
    environment:
      SERVICES_PORT: "http://services:${SERVICES_PORT}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  overview:
    container_name: overview
    build:
      context: "${LSEXTPATH}/redef/overview"
    networks:
      - backend
    ports:
      - "${OVERVIEW_PORT}:${OVERVIEW_PORT}"
    environment:
      HOST: "${HOST}"
      PATRON_CLIENT_PORT: "8000"
      SERVICES_PORT: "8005"
      CATALINKER_PORT: "8010"
      KOHA_OPAC_PORT: "8080"
      KOHA_INTRA_PORT: "8081"
      JAMON_PORT: "5070"
      TRIPLESTORE_PORT: "${TRIPLESTORE_PORT}"
      ELASTICSEARCH_PORT: "${ELASTICSEARCH_PORT}"
      KOHA_VERSION: "${KOHA_IMAGE_TAG}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  cuke_tests:
    container_name: cuke_tests
    build:
      context: "${LSEXTPATH}/test"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${LSEXTPATH}/test:/tests"
    environment:
      HOST: "${HOST}"
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "${KOHA_INSTANCE}"

  z3950proxy:
    container_name: z3950proxy
    image: "digibib/z3950proxy"
    networks:
      - backend
    environment:
      APPSECRET: "${Z3950SECRET}"
      BS_SERVER: "${BS_SERVER}"
      BS_PORT: "${BS_PORT}"
      BS_DB: "${BS_DB}"
      BS_USER: "${BS_USER}"
      BS_PASS: "${BS_PASS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
