---
version: '2'

networks:
  backend:
    driver: bridge

volumes:
  koha_state: {}

services:
  koha:
    container_name: koha
    image: "digibib/koha:${KOHA_IMAGE_TAG}"
    networks:
      - backend
    depends_on:
      - koha_mysql
      - koha_index
      - smtp
      - sip
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
      - MKNOD
    environment:
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "$KOHA_INSTANCE"
      KOHA_DBHOST: koha_mysql
      DEFAULT_LANGUAGE: nb-NO
      EMAIL_ENABLED: "True"
      SMTP_SERVER_HOST: mailrelay # access through network 'backend'
      SMTP_SERVER_PORT: 2525
      MESSAGE_QUEUE_FREQUENCY: 1
      SMS_SERVER_HOST: "${SMS_SERVER_HOST}"
      SMS_USER: "${SMS_USER}"
      SMS_PASS: "${SMS_PASS}"
      API_PASSPHRASE: "${API_PASSPHRASE}"
      NLBASEUSER: "${NLBASEUSER}"
      NLBASEPASS: "${NLBASEPASS}"
      NLVENDORURL: "${NLVENDORURL}"
      NLVENDORUSER: "${NLVENDORUSER}"
      NLVENDORPASS: "${NLVENDORPASS}"
      NLVENDORKEY: "${NLVENDORKEY}"
    ports:
      - "6001:6001"
      - "8081:8081"
    volumes_from:
      - koha_index
    volumes:
      - koha_state:/var/lib/state
    logging:
      driver: "journald"

  koha_mysql:
    container_name: koha_mysql
    image: mysql:5.6.20
    networks:
      - backend
    cap_add:
      - MKNOD
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
    environment:
      MYSQL_DATABASE: "koha_${KOHA_INSTANCE}"
      MYSQL_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_ROOT_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_USER: "${KOHA_ADMINUSER}"
    volumes_from:
      - koha_mysql_data
    logging:
      driver: "journald"

  koha_mysql_data:
    container_name: koha_mysql_data
    image: "busybox:latest"
    volumes:
      - /var/lib/mysql

  koha_index:
    container_name: koha_index
    image: "busybox:latest"
    volumes:
      - "/var/lib/koha/${KOHA_INSTANCE}"

  koha_state:
    container_name: koha_state
    image: "busybox:latest"
    volumes:
      - "/var/lib/state"

  memcached:
    container_name: memcached
    image: "memcached:1.4.25"
    networks:
      - backend

  rfidhub:
    container_name: rfidhub
    image: "digibib/rfidhub:7378d8f39f9c54fa388e42bce7100ac22d6cfb67"
    networks:
      - backend
    depends_on:
      - sip
    ports:
      - "6006:6006"
      - "8899:8899"
    environment:
      SIP_SERVER: sip:6002
      SIP_CONNS: 10
      TCP_PORT: 6006
    logging:
      driver: "journald"

  smtp:
    container_name: mailrelay
    image: "digibib/gosmtpd:e51ec0b872867560461ab1e8c12b10fd63f5d3c1"
    networks:
      - backend
    environment:
      FORWARD_SMTP: "${FORWARD_SMTP}"
    logging:
      driver: "journald"

  elasticsearch_data:
    container_name: elasticsearch_data
    image: "busybox:latest"
    volumes:
      - /usr/share/elasticsearch/data

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.3.1
    networks:
      - backend
    volumes_from:
      - elasticsearch_data
    logging:
      driver: "journald"

  fuseki_data:
    container_name: fuseki_data
    image: "busybox:latest"
    volumes:
      - /data/databases/ds

  fuseki:
    container_name: fuseki
    image: "digibib/fuseki2"
    networks:
      - backend
    volumes_from:
      - fuseki_data
    logging:
      driver: "journald"

  sip:
    container_name: sip_proxy
    image: "digibib/tcp-proxy:14dc5417bf211317351a0bae084db12c64a1dd45"
    networks:
      - backend
    ports:
      - "6002:9999"
    command:
      - "/app/tcp-proxy"
      - "-vv"
      - "-r"
      - "koha:${SIP_PORT}"
      - "-replace=AB100301~AB0301"
    logging:
      driver: "journald"

  catalinker:
    container_name: catalinker
    image: "digibib/redef-catalinker:${GITREF}"
    networks:
      - backend
    depends_on:
      - services
      - z3950proxy
    ports:
      - "8010:8010"
    environment:
      KOHA_OPAC_PORT: "http://koha:8080"
      KOHA_INTRA_PORT: "http://koha:8081"
      SERVICES_PORT: "http://services:8005"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "journald"

  services:
    container_name: services
    image: "digibib/redef-services:${GITREF}"
    networks:
      - backend
    depends_on:
      - fuseki
      - koha
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
      KOHA_API_PASS_ENCRYPTED: "${KOHA_API_PASS_ENCRYPTED}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "journald"

  patron-client:
    container_name: patron_client
    image: "digibib/redef-patron-client:${GITREF}"
    networks:
      - backend
    depends_on:
      - services
    ports:
      - "8000:8000"
    environment:
      SERVICES_PORT: "http://services:${SERVICES_PORT}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
    logging:
      driver: "journald"

  overview:
    container_name: overview
    build:
      context: "${OVERVIEW_BUILD_DIR}"
    networks:
      - backend
    ports:
      - "${OVERVIEW_PORT}:${OVERVIEW_PORT}"
    environment:
      HOST: "${HOST}"
      PATRON_CLIENT_PORT: "8000"
      SERVICES_PORT: "8005"
      CATALINKER_PORT: "8010"
      KOHA_OPAC_PORT: "8080"
      KOHA_INTRA_PORT: "8081"
      JAMON_PORT: "5070"
      TRIPLESTORE_PORT: "${TRIPLESTORE_PORT}"
      ELASTICSEARCH_PORT: "${ELASTICSEARCH_PORT}"
      KOHA_VERSION: "${KOHA_IMAGE_TAG}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "journald"

  z3950proxy:
    container_name: z3950proxy
    image: "digibib/z3950proxy"
    networks:
      - backend
    environment:
      APPSECRET: "${Z3950SECRET}"
      BS_SERVER: "${BS_SERVER}"
      BS_PORT: "${BS_PORT}"
      BS_DB: "${BS_DB}"
      BS_USER: "${BS_USER}"
      BS_PASS: "${BS_PASS}"
    logging:
      driver: "journald"

  migration:
    container_name: migration
    build:
      context: "${LSEXTPATH}/docker-compose/dockerfiles/migration"
      args:
        - MYSQL_DATABASE=koha_${KOHA_INSTANCE}
        - MYSQL_USER=${KOHA_ADMINUSER}
        - MYSQL_PASSWORD=${KOHA_ADMINPASS}
    networks:
      - backend
